[package]
name = "envcmd"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.27"

[profile.release]
opt-level = 3
strip = true
lto = true
