name: Main Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Build
        run: go build -o ./bin/envcmd .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/envcmd
